# Generated by Django 5.2.17 on 2026-09-28 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('desk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offsetsubmission',
            name='return_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='offsetsubmission',
            name='status',
            field=models.CharField(choices=[('pending', '待复核'), ('processing', '复核中'), ('done', '已完成'), ('returned', '已退回')], db_index=True, default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='RosterTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_code', models.CharField(max_length=32, unique=True)),
                ('state', models.CharField(choices=[('investable', '可投'), ('delisted', '已摘牌')], db_index=True, default='investable', max_length=16)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('delisted_at', models.DateTimeField(blank=True, null=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_tools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tool_code'],
            },
        ),
        migrations.CreateModel(
            name='RosterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_code', models.CharField(max_length=32)),
                ('action', models.CharField(choices=[('registered', '登记'), ('relisted', '勾可投'), ('delisted', '摘牌')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_events', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='desk.rostertool')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='offsetsubmission',
            name='roster_tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='desk.rostertool'),
        ),
    ]
